// Implement an asynchronous version of the extraction routine to improve scalability.

using System;
using System.IO;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Diagnostics;

class MemoryStreamProvider : Aspose.Html.IO.ICreateStreamProvider, IDisposable
{
    private readonly List<MemoryStream> _streams = new List<MemoryStream>();

    public IReadOnlyList<MemoryStream> Streams => _streams.AsReadOnly();

    public Stream GetStream(string name, string extension)
    {
        var ms = new MemoryStream();
        _streams.Add(ms);
        return ms;
    }

    public Stream GetStream(string name, string extension, int page)
    {
        var ms = new MemoryStream();
        _streams.Add(ms);
        return ms;
    }

    public void ReleaseStream(Stream stream)
    {
        if (stream != null)
        {
            stream.Flush();
        }
    }

    public void Dispose()
    {
        foreach (var ms in _streams)
        {
            ms.Dispose();
        }
        _streams.Clear();
    }
}

class Program
{
    static async Task Main()
    {
        try
        {
            string inputPath = "sample.epub";
            string outputPath = "output.xps";
            string logPath = "log.txt";

            // Ensure log file exists
            File.AppendAllText(logPath, $"Conversion started at {DateTime.Now}{Environment.NewLine}");

            // Open input stream
            using (Stream inputStream = File.OpenRead(inputPath))
            {
                var options = new Aspose.Html.Saving.XpsSaveOptions();

                using (var provider = new MemoryStreamProvider())
                {
                    var start = DateTime.Now;

                    await Task.Run(() =>
                        Aspose.Html.Converters.Converter.ConvertEPUB(inputStream, options, provider)
                    );

                    var end = DateTime.Now;
                    var elapsed = end - start;
                    File.AppendAllText(logPath, $"Conversion finished in {elapsed.TotalSeconds} seconds{Environment.NewLine}");

                    if (provider.Streams.Count > 0)
                    {
                        var firstStream = provider.Streams[0];
                        firstStream.Position = 0;
                        using (var fileStream = File.Create(outputPath))
                        {
                            firstStream.CopyTo(fileStream);
                        }
                        File.AppendAllText(logPath, $"First stream saved to {outputPath}{Environment.NewLine}");
                    }
                    else
                    {
                        File.AppendAllText(logPath, "No streams were generated by the conversion." + Environment.NewLine);
                    }
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}