// Create an empty HTML document, add a paragraph element, and save it as HTML.

using System;

class Program
{
    static void Main()
    {
        try
        {
            // Define output file path
            string outputPath = "output.html";

            // Create a new HTML document
            Aspose.Html.HTMLDocument doc = new Aspose.Html.HTMLDocument();

            // Get the body element
            Aspose.Html.HTMLElement body = doc.Body;

            // Create <h1> element with text
            Aspose.Html.HTMLHeadingElement h1 = (Aspose.Html.HTMLHeadingElement)doc.CreateElement("h1");
            Aspose.Html.Dom.Text txtH1 = doc.CreateTextNode("Hello, Aspose.HTML!");
            h1.AppendChild(txtH1);

            // Create <p> element with text
            Aspose.Html.HTMLParagraphElement p = (Aspose.Html.HTMLParagraphElement)doc.CreateElement("p");
            Aspose.Html.Dom.Text txtP = doc.CreateTextNode("This is a sample paragraph generated by Aspose.HTML for .NET.");
            p.AppendChild(txtP);

            // Append elements to the body
            body.AppendChild(h1);
            body.AppendChild(p);

            // Save the document to the specified path
            doc.Save(outputPath);

            Console.WriteLine($"HTML document successfully saved to '{outputPath}'.");
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred: " + ex.Message);
        }
    }
}