// Measure conversion time by recording timestamps before and after calling Converter.ConvertEPUB for performance analysis.

using System;
using System.IO;
using System.Collections.Generic;
using System.Diagnostics;
using Aspose.Html.IO;
using Aspose.Html.Saving;
using Aspose.Html.Converters;

class MemoryStreamProvider : ICreateStreamProvider, IDisposable
{
    private readonly List<MemoryStream> _streams = new List<MemoryStream>();

    public IReadOnlyList<MemoryStream> Streams => _streams;

    public Stream GetStream(string name, string extension)
    {
        var ms = new MemoryStream();
        _streams.Add(ms);
        return ms;
    }

    public Stream GetStream(string name, string extension, int page)
    {
        var ms = new MemoryStream();
        _streams.Add(ms);
        return ms;
    }

    public void ReleaseStream(Stream stream)
    {
        // No action needed; streams are kept for later use.
    }

    public void Dispose()
    {
        foreach (var ms in _streams)
        {
            ms.Dispose();
        }
        _streams.Clear();
    }
}

class Program
{
    static void Main()
    {
        try
        {
            // Input EPUB file path (replace with an existing file or create a minimal one)
            string inputPath = "sample.epub";
            // Output XPS file path (first generated stream will be saved here)
            string outputPath = "output.xps";

            // Ensure a sample EPUB file exists (minimal placeholder)
            if (!File.Exists(inputPath))
            {
                // Create an empty file just for demonstration; real conversion requires valid EPUB content.
                File.WriteAllBytes(inputPath, new byte[0]);
            }

            using (Stream inputStream = File.OpenRead(inputPath))
            {
                XpsSaveOptions options = new XpsSaveOptions();

                MemoryStreamProvider provider = new MemoryStreamProvider();

                Stopwatch sw = new Stopwatch();
                sw.Start();

                Aspose.Html.Converters.Converter.ConvertEPUB(inputStream, options, provider);

                sw.Stop();
                Console.WriteLine($"Conversion elapsed time: {sw.Elapsed}");

                if (provider.Streams.Count > 0)
                {
                    MemoryStream firstStream = provider.Streams[0];
                    firstStream.Position = 0;
                    using (FileStream fileStream = File.Create(outputPath))
                    {
                        firstStream.CopyTo(fileStream);
                    }
                    Console.WriteLine($"First generated XPS saved to: {outputPath}");
                }
                else
                {
                    Console.WriteLine("No streams were generated by the conversion.");
                }

                provider.Dispose();
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}