// Add a YAML front‑matter block at the top with custom metadata fields for the document.

/*
---
title: Aspose.HTML Console Example
author: ChatGPT
date: 2026-10-01
---
*/

public class Program
{
    public static void Main(string[] args)
    {
        try
        {
            // Create a new empty HTML document
            Aspose.Html.HTMLDocument document = new Aspose.Html.HTMLDocument();

            // Get the body element
            Aspose.Html.HTMLElement body = document.Body;

            // Create and add a heading
            Aspose.Html.HTMLHeadingElement h1 = (Aspose.Html.HTMLHeadingElement)document.CreateElement("h1");
            h1.AppendChild(document.CreateTextNode("Hello Aspose.HTML!"));
            body.AppendChild(h1);

            // Create and add a paragraph
            Aspose.Html.HTMLParagraphElement p = (Aspose.Html.HTMLParagraphElement)document.CreateElement("p");
            p.AppendChild(document.CreateTextNode("This is a sample paragraph generated by Aspose.HTML for .NET."));
            body.AppendChild(p);

            // Save the document to a file
            document.Save("output.html");
        }
        catch (System.Exception ex)
        {
            System.Console.WriteLine("Error: " + ex.Message);
        }
    }
}