// Add a YAML front‑matter block at the top with custom metadata fields for the document.

/*
---
title: "Aspose.HTML Sample Document"
author: "ChatGPT"
date: "2026-09-24"
---
*/

using System;

class Program
{
    static void Main()
    {
        try
        {
            // Create a new HTML document
            Aspose.Html.HTMLDocument document = new Aspose.Html.HTMLDocument();

            // Get the body element
            Aspose.Html.HTMLElement body = document.Body;

            // Create a heading element
            Aspose.Html.HTMLHeadingElement h1 = (Aspose.Html.HTMLHeadingElement)document.CreateElement("h1");
            h1.AppendChild(document.CreateTextNode("Hello, Aspose.HTML!"));
            body.AppendChild(h1);

            // Create a paragraph element
            Aspose.Html.HTMLParagraphElement paragraph = (Aspose.Html.HTMLParagraphElement)document.CreateElement("p");
            paragraph.AppendChild(document.CreateTextNode("This is a sample paragraph generated by Aspose.HTML for .NET."));
            body.AppendChild(paragraph);

            // Save the document to a file
            string outputPath = "output.html";
            document.Save(outputPath);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Error: " + ex.Message);
        }
    }
}