// Add an author metadata comment at the beginning of the Markdown file for documentation purposes.

// Author: John Doe
using System;
using System.IO;
using Aspose.Html;
using Aspose.Html.Converters;
using Aspose.Html.Saving;

class Program
{
    static void Main()
    {
        try
        {
            // Define output directory
            string outputDir = Path.Combine(Directory.GetCurrentDirectory(), "output");
            Directory.CreateDirectory(outputDir);

            // Define source markdown file path
            string sourcePath = Path.Combine(outputDir, "document.md");

            // Markdown content with author metadata comment
            string markdownContent = "<!-- Author: John Doe -->\n# Sample Document\n\nThis is a sample markdown file generated by Aspose.HTML.";

            // Write markdown content to file
            File.WriteAllText(sourcePath, markdownContent);

            // Define output DOCX file path
            string savePath = Path.Combine(outputDir, "document-output.docx");

            // Convert Markdown to HTMLDocument
            Aspose.Html.HTMLDocument document = Aspose.Html.Converters.Converter.ConvertMarkdown(sourcePath);

            // Convert HTMLDocument to DOCX
            Aspose.Html.Saving.DocSaveOptions docOptions = new Aspose.Html.Saving.DocSaveOptions();
            Aspose.Html.Converters.Converter.ConvertHTML(document, docOptions, savePath);

            // Clean up
            document.Dispose();

            Console.WriteLine("Conversion completed successfully.");
            Console.WriteLine($"Markdown file: {sourcePath}");
            Console.WriteLine($"DOCX file: {savePath}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}