// Use a using block to ensure FileStream disposal after writing converted XPS data to disk.

using System;
using System.IO;
using System.Collections.Generic;

class MemoryStreamProvider : Aspose.Html.IO.ICreateStreamProvider, IDisposable
{
    public List<MemoryStream> Streams { get; } = new List<MemoryStream>();

    public Stream GetStream(string name, string extension)
    {
        var ms = new MemoryStream();
        Streams.Add(ms);
        return ms;
    }

    public Stream GetStream(string name, string extension, int page)
    {
        var ms = new MemoryStream();
        Streams.Add(ms);
        return ms;
    }

    public void ReleaseStream(Stream stream)
    {
        if (stream != null)
        {
            stream.Flush();
        }
    }

    public void Dispose()
    {
        foreach (var ms in Streams)
        {
            ms.Dispose();
        }
    }
}

class Program
{
    static void Main()
    {
        string inputPath = "sample.epub";
        string outputPath = "output.xps";

        // Ensure a sample input file exists (empty file for demonstration)
        if (!File.Exists(inputPath))
        {
            File.WriteAllBytes(inputPath, new byte[0]);
        }

        try
        {
            using (Stream inputStream = File.OpenRead(inputPath))
            {
                using (var provider = new MemoryStreamProvider())
                {
                    var options = new Aspose.Html.Saving.XpsSaveOptions();

                    // Perform conversion
                    Aspose.Html.Converters.Converter.ConvertEPUB(inputStream, options, provider);

                    if (provider.Streams.Count > 0)
                    {
                        MemoryStream resultStream = provider.Streams[0];
                        resultStream.Position = 0;

                        using (Stream output = File.Create(outputPath))
                        {
                            resultStream.CopyTo(output);
                        }

                        Console.WriteLine($"Conversion succeeded. Output saved to: {outputPath}");
                    }
                    else
                    {
                        Console.WriteLine("No output streams were generated by the conversion.");
                    }
                }
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("An error occurred during conversion: " + ex.Message);
        }
    }
}